service: phlex-icons

image: aliosm/phlex-icons

registry:
  username: aliosm

  password:
    - KAMAL_REGISTRY_PASSWORD

servers:
  web:
    hosts:
      - 54.247.196.28

proxy:
  host: phlex-icons.fun
  ssl: true
  healthcheck:
    path: /up

# Remember to run `kamal env push` after making changes!
env:
  secret:
    - RAILS_MASTER_KEY

asset_path: /rails/public/assets

ssh:
  user: ubuntu

builder:
  arch: amd64
  remote: ssh://ubuntu@54.247.196.28
